### ISSUE TITLE
package ‘PCAtools’ is not available (for R version 3.5.1)

### ISSUE THREAD

**Issue by GryderArt** [kevinblighe/PCAtools#15]
package ‘PCAtools’ is not available (for R version 3.5.1)

is there a way to get around this?

**Comment by kevinblighe** [comment]
Hey, you can probably install the development version via:

```
devtools::install_github('kevinblighe/PCAtools')
```

Let me know if that works.

**Comment by kevinblighe** [comment]
Closing as no response.

**Comment by nmacknight** [comment]
I have the same issue, when I try to use:

devtools::install_github('kevinblighe/PCAtools')

I get a prompt to basically download a command line. Seems odd. Thank you for your time and suggestions.

**Comment by kevinblighe** [comment]
Hey, can you not install via BiocManager?
`BiocManager::install('PCAtools')`

**Comment by nmacknight** [comment]
Hey Kevin, thank you for your time. I ran

BiocManager::install('PCAtools')

as you suggested and received this error which may be because I recently updated my R to 3.6 to try and get PCAtools to cooperate,

Loading required package: ggplot2
Error: package or namespace load failed for ‘ggplot2’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘rlang’
Error: package ‘ggplot2’ could not be loaded

Any thoughts or suggestions are appreciated.

**Comment by kevinblighe** [comment]
I see... can you try to install rlang via BiocManager ?

**Comment by kevinblighe** [comment]
No response

**Comment by nmacknight** [comment]
`BiocManager::install("rlang")`

was successful. 

Thank you for your time.

**Comment by JTisanewcoder** [comment]
I have the same problem. I updated the R version from 3.6.2 to 3.6.3. It's the same warning " package ‘PCAtools’ is not available (for R version 3.6.3)'
And devtools and BiocManager can't download either

**Comment by kevinblighe** [comment]
Hi @JTisanewcoder, can you show the output that is produced after you try to install the package?

**Comment by JTisanewcoder** [comment]
> Hi @JTisanewcoder, can you show the output that is produced after you try to install the package?

Thank you so much. I tried many times and finally installed successfully using BiocManager::install(' ').

**Comment by luis-martinez-robles** [comment]
I have RNA-seq data, when I run:
`biplot(p)`
I get: 
Error: $ operator not defined for this S4 class
