### ISSUE TITLE
Legends with Long names for each meta data variable name get distorted in the legend 

### ISSUE THREAD

**Issue by jsalsager** [kevinblighe/PCAtools#3]
When I plot to a pdf, the legend is larger than the image and gets cut off on either end (when I stick the legend below the plot). When I put the legend next to the plot, it's really large and distorts the plot.

This is a really cool package though, thanks for making it!

**Comment by jsalsager** [comment]
![PCATools bus](https://user-images.githubusercontent.com/35507365/58194831-6b07b680-7c7b-11e9-8ebd-cde8e352d4fb.png)

**Comment by kevinblighe** [comment]
Hey, thanks for the message and thanks for using _PCAtools_

The easiest solution would be to simply shorten the names in your metadata, for example, 'estrogen receptor' can be easily changed to 'ER+' (?). The other one that you have shown in your screenshot could be shortened to 'ERBB2+' or 'HER2+' (?)

Otherwise, you may have to go a longer route and do things like add custom legends with endline charactesr ('\n'), but this can become long-winded and is not implemented in the package.
