### ISSUE TITLE
Any easy way to run PCAtools on Seurat Objects?

### ISSUE THREAD

**Issue by mr-september** [kevinblighe/PCAtools#36]
Hi, thank you for the great package!

I have been trying to run it with Seurat Objects, in particular to try the automatic "optimal" PCAs methods (Elbow, Horn’s parallel analysis, Marchenko-Pastur limit,Gavish-Donoho method).

I was trying to follow [this vignette](https://bioconductor.org/packages/release/bioc/vignettes/PCAtools/inst/doc/PCAtools.html), but it seems to set up and use a dataframe manually, while Seurat Objects are a little different.

But the key seems to be this line: 
` p <- pca(mat, metadata = metadata, removeVar = 0.1)`,
while Seurat's is: 
`RunPCA(data, features = VariableFeatures(object = data))`
with the VariableFeatures done in a previous step.

Is there any "translation" from `Seurat's VariableFeatures(object = data)` to PCAtools' `metadata`? 
Or otherwise, is there any way to use Seurat's `RunPCA` results on PCAtools' "optimal methods" finder, such as `parallelPCA(mat)` and `findElbowPoint(p$variance)`?

**Comment by LTLA** [comment]
In principle, you should be good to go if you can pull the PCA statistics out of the `Seurat` object. Whether they retain enough of it is another question, but if not, you could just call `pca()` yourself with the log-expression matrix and the HVGs. (Make sure you use one of the approximate PCA methods, though, if your dataset is of any decent size.)

The Gavish-Donoho and Marchenko-Pastur methods are slightly different in that they also require an estimate of the technical noise in the log-expression scale. AFAIK **Seurat** does not model variation in the transformed space; they either estimate the CV^2^ or the dispersion, depending on which workflow you use. For those methods, you'll have to use some other methods to estimate the noise - see the discussion in the corresponding chapter of the [OSCA book](http://bioconductor.org/books/release/OSCA/dimensionality-reduction.html#choosing-the-number-of-pcs).

Of course, you could just convert your `Seurat` object into an SCE and follow the book instructions verbatim.

@kevinblighe we should make those other functions work "natively" on the `pca()` output with minimal user specification of arguments. It may be worth considering support for a common PCA output format/class that we can define in **BiocNeighbors** so that the **PCAtools** downstream functions work regardless of who generates the PCs.
