### ISSUE TITLE
eigencorplot throws an error when plotting only a single variable 

### ISSUE THREAD

**Issue by sparsepix** [kevinblighe/PCAtools#55]
Hi,
when I try to plot the correlation of only a single variable with the PCs eigencorplot throws an error: 
```
 options(scipen=10)
  options(digits=6)

  col <- 20
  row <- 20000
  mat1 <- matrix(
    rexp(col*row, rate = 0.1),
    ncol = col)
  rownames(mat1) <- paste0('gene', 1:nrow(mat1))
  colnames(mat1) <- paste0('sample', 1:ncol(mat1))

  mat2 <- matrix(
    rexp(col*row, rate = 0.1),
    ncol = col)
  rownames(mat2) <- paste0('gene', 1:nrow(mat2))
  colnames(mat2) <- paste0('sample', (ncol(mat1)+1):(ncol(mat1)+ncol(mat2)))

  mat <- cbind(mat1, mat2)

  metadata <- data.frame(row.names = colnames(mat))
  metadata$Group <- rep(NA, ncol(mat))
  metadata$Group[seq(1,40,2)] <- 'A'
  metadata$Group[seq(2,40,2)] <- 'B'
  metadata$CRP <- sample.int(100, size=ncol(mat), replace=TRUE)
  metadata$ESR <- sample.int(100, size=ncol(mat), replace=TRUE)

  p <- pca(mat, metadata = metadata, removeVar = 0.1)

  eigencorplot(p, components = getComponents(p, 1:10),
    metavars = c('ESR')) 
```

`Warning in seq_len(ncol(pvals)) : first element used of 'length.out' argument
Error in seq_len(ncol(pvals)) : argument must be coercible to non-negative integer`

everything is working fine when plotting two variables 

`   eigencorplot(p, components = getComponents(p, 1:10), metavars = c('ESR','CRP'))`  

Another question: The `  ?eigencorplot`   text states the function should only be used with continuous variables. It does work however for discrete variables, too. Is there some problem with interpreting the results for discrete variables? 

Best, Niko

**Comment by kevinblighe** [comment]
Hi Niko,

Yes, unfortunately it will not work with just a single parameter - apologies about this. I may suggest that you duplicate the variable and then generate the plot for the original variable and the duplicate one, and then manually edit the plot. I cannot offer a better solution for now, and have no resources to develop further this package.

> Another question: The ?eigencorplot text states the function should only be used with continuous variables. It does work however for discrete variables, too. Is there some problem with interpreting the results for discrete variables?

With discrete variables, one has to be careful. The correlation will change depending on how the discrete variable is encoded as a factor, i.e., the order of the factors is important. For some things, it can make sense, like, for example, if Tumour grade is discrete and ordered in this way:
> Grade I, Grade II, Grade III, Grade IV

However, it would not make sense if ordered like this:
> Grade I, Grade IV, Grade II, Grade III

One can manually order discrete variables via `factor(x, levels = ('Grade I', 'Grade II', 'Grade III', 'Grade IV'))`

Kind regards,
Kevin

**Comment by ilobon** [comment]
Hi, 

I encountered the same issue and found a simple fix:

In the **eigencorplot** code, update this line
`pvals <- pvals[match(rownames(corvals), rownames(pvals)), ]`
to
`pvals <- pvals[match(rownames(corvals), rownames(pvals)), , drop = FALSE]`
This change ensures that pvals remains a data frame when reordering the rows, avoiding unintended conversion to a vector.
**Note**: The closing bracket ] for this line appears in the next line of the source code.

If you don’t want to alter the package itself, you can easily create a modified version of the function in your script:
1. Print the function's code:
`print(eigencorplot)`
2. Copy all the function code, from "function (" only excluding the last two lines that start with <
3. Paste the copied code in your script and assign it to a new name:
 `eigencorplot_1var<-function (...` 
4. Make the edit described above so that the drop = FALSE argument is added
5. Run the code so that the function is available

You can now use your modified function as usual, for example:
`eigencorplot_1var(p, metavars="Age"`

**Note:** I had to explicitly load lattice for the new function to work 
`library(lattice) `
